# Deploy this deployment Yaml using command as 
# store the image url in a temp variable on command prompt
# image_url='<path to Image:version'
#


apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: front-end
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
      version: v1
  template:
    metadata:
      labels:
        app: front-end
        version: v1
    spec:
      containers:
      - name: front-end
        image: IMAGE_URL
        ports:
        - containerPort: 80
        
        
