apiVersion: v1
kind: Service
metadata:
  name: simple-web-server-service
spec:
  selector:
    app: simple-web-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      